### ISSUE TITLE
Getting NullPointerException when trying to startActivityForResult from fragment

### ISSUE THREAD

**Issue by egkz** [JetradarMobile/android-multibackstack#9]
In my fragment I need to start activity for result but

```
 Process: com.magis.icbc, PID: 810
                  java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
                      at android.support.v4.app.BackStackRecord.doAddOp(BackStackRecord.java:392)
                      at android.support.v4.app.BackStackRecord.replace(BackStackRecord.java:439)
                      at android.support.v4.app.BackStackRecord.replace(BackStackRecord.java:430)
                      at com.magis.icbc.ui.components.activity.MainMenuActivity.replaceFragment(MainMenuActivity.java:428)
```

replace method gives NPE

```
private void replaceFragment(@NonNull Fragment fragment) {
    FragmentManager fm = getSupportFragmentManager();
    FragmentTransaction tr = fm.beginTransaction();
    tr.replace(R.id.frame_container, fragment);
    tr.commitAllowingStateLoss();
    curFragment = fragment;
  }
```

**Comment by egkz** [comment]
ok I guess this was a logcat malfunction showing the exception in the wrong place, turned out it was giving exception because I was calling getSupportActionBar() in NoActionBar theme. Closing the issue, it has nothing to do with the backstack

**Comment by kopilim96** [comment]
Does the issue solve ?
I think I have some idea and I solved my problem of the issue as yours
